---
title: "STAT3622_Project"
author: "Wang Peinan"
date: "2024-04-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exploratory Data Analysis
```{r}
library(ggplot2)
library(dplyr)
df <- read.csv('dataset_cleaned.csv', header = TRUE)
```

```{r}
# Pie Chart1
df_count <- df %>%
  group_by(`Primary.Type`) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))

ggplot(df_count, aes(x="", y=freq, fill=`Primary.Type`)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start=0) +
  theme_void() +
  theme(legend.position="right") +
  labs(fill="Primary Type") +
  geom_text(aes(label = paste0(round(freq*100, 1), "%")), position = position_stack(vjust = 1))
```

```{r}
# Pie Chart2
df_count <- df %>%
  group_by(UCR_PART) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))

ggplot(df_count, aes(x="", y=freq, fill=UCR_PART)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start=0) +
  theme_void() +
  theme(legend.position="right") +
  labs(fill="UCR_PART") +
  geom_text(aes(label = paste0(round(freq*100, 1), "%")), position = position_stack(vjust = 0.5))
```

```{r}
# Primary Type v.s. UCR_PART
df_count <- df %>%
  group_by(`Primary.Type`, UCR_PART) %>%
  summarise(count = n(), .groups = "drop") %>%
  arrange(desc(count)) %>%
  mutate(`Primary.Type` = reorder(`Primary.Type`, +count))

color_dict <- c("UCR_PART_I" = "orange", "UCR_PART_II" = "blue")

ggplot(df_count, aes(x=`Primary.Type`, y=count, fill=UCR_PART)) +
  geom_bar(stat="identity", position="dodge") +
  scale_fill_manual(values=color_dict) +
  labs(title="Number of Crimes by Primary Type", x="Primary Type", y="Count", fill="UCR_PART") +
  theme_minimal() +
  coord_flip()
```

```{r}
# Trends of the crimes over the years (2014 - 2023)
df_count <- df %>%
  group_by(Year, UCR_PART) %>%
  summarise(count = n())

color_dict <- c("UCR_PART_I" = "orange", "UCR_PART_II" = "blue")

ggplot(df_count, aes(x=Year, y=count, color=UCR_PART)) +
  geom_line(linewidth = 1.5) +
  scale_color_manual(values=color_dict) +
  labs(title="Number of Crimes by Year", x="Year", y="Count", color="UCR_PART") +
  theme_minimal()
```

```{r}
# Number of Crimes by Month
df_count <- df %>%
  group_by(Month, UCR_PART) %>%
  summarise(count = n())

color_dict <- c("UCR_PART_I" = "orange", "UCR_PART_II" = "blue")

ggplot(df_count, aes(x=Month, y=count, fill=UCR_PART)) +
  geom_bar(stat="identity", position="dodge") +
  scale_fill_manual(values=color_dict) +
  labs(title="Number of Crimes by Month", x="Month", y="Count", fill="UCR_PART") +
  theme_minimal()
```

```{r}
# Number of Crimes by Time
library(tidyr)

df <- df %>%
  drop_na(Time)

df$Time <- factor(df$Time, levels = c("Early Morning", "Late Morning", "Afternoon", "Night"))

df_count <- df %>%
  group_by(Time, UCR_PART) %>%
  summarise(count = n())

color_dict <- c("UCR_PART_I" = "orange", "UCR_PART_II" = "blue")

ggplot(df_count, aes(x=Time, y=count, fill=UCR_PART)) +
  geom_bar(stat="identity", position="dodge") +
  scale_fill_manual(values=color_dict) +
  labs(title="Number of Crimes by Time", x="Time", y="Count", fill="UCR_PART") +
  theme_minimal()
```

```{r}
library(maps)
library(mapdata)

usa_map <- map_data("state")
chicago_map <- subset(usa_map, region %in% c("illinois"))

ggplot() +
  geom_polygon(data = chicago_map, aes(x = long, y = lat, group = group), fill = "white", color = "black") +
  geom_point(data = df, 
             aes(x = Longitude, y = Latitude, color = factor(UCR_PART)), 
             alpha = 0.5) +
  scale_color_discrete(name = "UCR_PART", 
                       labels = c("1" = "Category 1", "2" = "Category 2")) +
  coord_fixed(1.3) +
  coord_cartesian(xlim = c(-87.9, -87.5), ylim = c(41.6, 42.1)) +
  theme_minimal() +
  labs(title = "Point plot on Chicago map", 
       x = "Longitude", 
       y = "Latitude")
```










